Allow users to export or import user-settings file in a GUI environment
sqlitebrowser/sqlitebrowser pull request #2394
Opened 2020-09-13 09:25 UTC by lucydodo

This patch changes to allow users to export or import user-settings file in a GUI environment.
This PR is related to issue #2393.

Detailed Changes
--------------------
1. There was an opinion that the expression 'Settings' is more appropriate than 'Configuration' or 'Preferences'
So it is be changed to 'Settings' and also, the following two command line options change accordingly:
    - `-p [preferences_file]` -> `-S [settings_file]`
    - `--preferences [preferences_file]` -> `--settings [settings_file]`
2. Add the following two buttons to the 'PreferencesDialog'
    - Export Settings
    - Import Settings

Need Help
------------
In issue #2393, @chrisjlocke showed a prototype of a new buttons to the left of the existing 'Restore Defaults` button.
I thought this is better, so I tried but failed due to my lack of ability. May I get any advice on this part?

Test Environment
-------------------
- macOS Catalina (10.15.6, 19G2021)
- Ubuntu Desktop 20.04.1

Thank you.

2020-09-19 14:48 UTC, mgrojo requested changes
Nice feature and good implementation. Please, take into account just a pair of minor changes requested.

2020-09-19 14:48 UTC, mgrojo commented on src/Settings.cpp
> +    foreach(QString currentGroup, groups)
Do not use Qt's foreach, they can be considered obsolete after C++11 introduced [range-base for loops](https://en.cppreference.com/w/cpp/language/range-for).

2020-09-19 14:48 UTC, mgrojo commented on src/Settings.h
> +    static bool verifyUserSettingsFile(const QString userSettingsFile);
Consider calling this `isValidSettingsFile()`; it will give the developer the instant recognition that it returns a boolean.

2020-09-19 14:48 UTC, mgrojo commented on src/Settings.cpp
> +        foreach(QString currentKey, keys)
The same advice.

2020-09-19 15:26 UTC, lucydodo commented
Thanks for the review. I just modified and committed it. Could you take a look?

2020-09-19 20:36 UTC, mgrojo approved these changes

2020-09-19 20:38 UTC, merged

2020-09-19 20:39 UTC, mgrojo commented
Awesome! Another feature in development version. :+1:

2020-09-20 10:22 UTC, mgrojo commented
By the way, there is room for improvement about having to restart the application to apply the settings. Have you tried to make that work? We have the same problem when changing the language, but I suppose there could be problems due to Qt limitations (I haven't investigated it myself though). But maybe in this case it's just a matter of calling `Settings::setValue()` instead of invoking `QSettings` directly, and then get `MainWindow` to call `reloadSettings()`. Maybe a call to accept() at the end of `PreferencesDialog::importSettings()` would make the trick? I suppose that would do it, since it is what "restore defaults" is doing.

2020-09-20 12:08 UTC, lucydodo commented
Yes, that's a good point.

It can be applied immediately by
call `accept()` in `PreferencesDialog.cpp:importSettings()`,
and call `m_hCache.clear()` in `Settings.cpp:importSettings()`

However, since the 'language' is also included in the settings file, I decided to request a restart.
If necessary, we can detect if there is a language change and only require a restart.

2020-09-20 14:11 UTC, mgrojo commented
Yes, that makes sense.

2020-09-20 14:25 UTC, lucydodo commented
Which method do you think is better?

1. Keep the old way
2. If the language settings is not changed, the settings is reflect immediately(work like 'Restore Defaults')
3. When the language settings is changed, a warning indicating to restart
4. When the language settings is changed, restart via code after warning(with QApplication, QProcess)

2020-09-20 14:40 UTC, mgrojo commented
I think 2 and 3 is the best approach. 3 should reuse the current message dialog for notifying the user.

2020-09-20 14:43 UTC, lucydodo commented
OK. Let's proceed with the modification. :)

2020-09-20 16:03 UTC, lucydodo commented
One more thing, I think we need save settings before export settings.
What do you reckon? @mgrojo

2020-09-20 19:34 UTC, mgrojo commented
I see. Having these buttons in the Preferences dialog complicates the implementation. Maybe you have to split (or add a parameter to) `saveSettings` so you can save the data without calling `accept`, and call `accept` once the file has been chosen and saved.

2020-09-21 03:28 UTC, lucydodo commented
Cool, this is a simple fix so I just committed it to the master branch without pr. 0031d9ae4098a3a22480eaab58256913e6880d05