SpatiaLite to SVG display format
sqlitebrowser/sqlitebrowser pull request #2767
Opened 2021-07-12 13:47 UTC by sandman7920

2021-07-12 14:10 UTC, justinclift commented
Cool.  When we merge this, lets do:

* A blog post with at least an example + screenshot
* Make sure the nightly builds have been run, so we can point people at downloads that have the functionality for this in it

Pretty sure it'll be a useful feature for people that do GIS stuff. :smile:

2021-07-13 19:05 UTC, mgrojo requested changes
Nice work! Please check the duplicated line, which seems unintended, but otherwise, I think it can be merged.

2021-07-13 21:14 UTC, sandman7920 commented on src/ImageViewer.ui
> +  <include location="icons/icons.qrc"/>
> 
> 
> Is this intended?

Uhh no, somehow Qt Creator added this automatically

2021-07-13 21:25 UTC, mgrojo commented on src/ImageViewer.ui
> +  <include location="icons/icons.qrc"/>
Sometimes Creator makes funny things with UI files. It's a good idea to review them for any undesired change.

2021-07-14 06:51 UTC, merged

2021-07-19 14:29 UTC, justinclift commented
Ahhh, cool.  Didn't realise this had been merged.

We should probably do some promo of this via the website or something.

@sandman7920 Do you have an example database with SVG data in it that I can load and take some screenshots of?  Hmmm, unless you're ok to do the screenshots, and I'll throw them on the website in a blog post.

Oh, if you want to write blog post stuff, you're definitely welcome to.  No-one else but me seems to, and I'd like to kind of spread that around a bit. :wink:

2021-08-02 08:14 UTC, sandman7920 commented
@justinclift I have posted in the developer's team, I don't know if you read the post.

2021-08-02 13:26 UTC, justinclift commented
Sorry, yeah.  It's just been a very busy few weeks.  I'll get around to it in the near-ish future. :smile:

As a reminder, everyone in the team has write access to the blog.  So, everyone can write blog posts and they'll automatically appear on the website (it checks and updates every 10 mins). :grin: